project_id = "opsnerve-performance-analyzer"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:3000"

[storage]
enabled = true
