-- 00019_enable_rls.sql
-- Enable RLS on all tables. No access until policies are created.

ALTER TABLE academies ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE video_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE cv_tracks ENABLE ROW LEVEL SECURITY;
ALTER TABLE cv_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE wearable_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE wearable_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE cv_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE tactical_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_baselines ENABLE ROW LEVEL SECURITY;
ALTER TABLE load_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_queries ENABLE ROW LEVEL SECURITY;
ALTER TABLE highlight_reels ENABLE ROW LEVEL SECURITY;
ALTER TABLE development_snapshots ENABLE ROW LEVEL SECURITY;
